# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ccMbdeq6YhbYErrGV8SbFIEb0gxVCqq
"""

# ============================================================
# Gemini 2.5 Flash API Integration — FIXED
# ============================================================

import requests
import json

# --- Configuration ---
API_KEY = "YOUR_API_KEY"   # From Google AI Studio
ENDPOINT = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"

def query_gemini(prompt: str, debug: bool = False) -> str:
    headers = {
        "Content-Type": "application/json",
        "x-goog-api-key": API_KEY        # ← key in header, not query param
    }

    payload = {
        "contents": [
            {
                "parts": [{"text": prompt}]
            }
        ]
    }

    response = requests.post(ENDPOINT, headers=headers, json=payload)
    response.raise_for_status()

    data = response.json()

    if debug:
        print("\n--- RAW PAYLOAD ---")
        print(json.dumps(data, indent=2))
        print("-------------------\n")

    return data["candidates"][0]["content"]["parts"][0]["text"]


# ============================================================
# Interactive CLI for Colab
# ============================================================
def run_cli():
    print("Gemini 2.5 Flash | Type 'exit' to quit, add --debug for raw payload\n")
    while True:
        user_input = input("Prompt: ").strip()
        if user_input.lower() == "exit":
            break

        debug_mode = False
        if user_input.endswith("--debug"):
            debug_mode = True
            user_input = user_input.replace("--debug", "").strip()

        if not user_input:
            continue

        try:
            result = query_gemini(user_input, debug=debug_mode)
            print(f"\nGemini: {result}\n")
        except requests.HTTPError as e:
            print(f"\nHTTP Error: {e.response.status_code} - {e.response.text}\n")
        except Exception as e:
            print(f"\nError: {e}\n")

run_cli()
