# -*- coding: utf-8 -*-
"""vector_search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hEEMO2TY6O6DSYsI4s-ZIjd8Yx7KAIa
"""

from sentence_transformers import SentenceTransformer
import numpy as np

# 1. Load the model
model = SentenceTransformer("intfloat/e5-small-v2")

# 2. Example sentences (you can replace with PDF text)
sentences = [
    "Artificial intelligence is transforming industries.",
    "Machine learning is a subset of AI.",
    "Deep learning uses neural networks.",
    "Natural language processing helps machines understand text.",
    "Computer vision enables machines to interpret images."
]

# 3. Add required prefix for E5 model
passages = ["passage: " + sentence for sentence in sentences]

# 4. Convert sentences into embeddings
passage_embeddings = model.encode(passages, normalize_embeddings=True)

# 5. Define similarity function (cosine similarity)
def cosine_similarity(a, b):
    return np.dot(a, b)

# 6. Query input
query = "What is machine learning?"
query_embedding = model.encode("query: " + query, normalize_embeddings=True)

# 7. Compute similarity scores
scores = [cosine_similarity(query_embedding, emb) for emb in passage_embeddings]

# 8. Get best match
best_index = np.argmax(scores)

# 9. Output result
print("Query:", query)
print("Best Match:", sentences[best_index])
print("Score:", scores[best_index])
